insert into public.user_settings (
  user_id,
  portfolio_value,
  timezone,
  email_notifications_enabled,
  digest_email_enabled,
  urgent_alerts_enabled,
  notification_email,
  scan_schedule,
  buy_signal_expiry_days,
  morning_trade_monitor_enabled,
  screener_enabled,
  screener_min_price,
  screener_min_avg_volume,
  screener_min_eps_growth_pct,
  screener_min_revenue_growth_pct,
  screener_exchanges,
  screener_max_candidates
)
values (
  '89b2a201-04fb-4c5e-8d42-bdb0c89c42ff',
  100000,
  'America/Denver',
  true,
  true,
  true,
  null,
  'evening_only',
  1,
  true,
  true,
  10,
  500000,
  25,
  20,
  'XNAS,XNYS',
  20
)
on conflict (user_id) do update
set
  portfolio_value = excluded.portfolio_value,
  timezone = excluded.timezone,
  email_notifications_enabled = excluded.email_notifications_enabled,
  digest_email_enabled = excluded.digest_email_enabled,
  urgent_alerts_enabled = excluded.urgent_alerts_enabled,
  notification_email = excluded.notification_email,
  scan_schedule = excluded.scan_schedule,
  buy_signal_expiry_days = excluded.buy_signal_expiry_days,
  morning_trade_monitor_enabled = excluded.morning_trade_monitor_enabled,
  screener_enabled = excluded.screener_enabled,
  screener_min_price = excluded.screener_min_price,
  screener_min_avg_volume = excluded.screener_min_avg_volume,
  screener_min_eps_growth_pct = excluded.screener_min_eps_growth_pct,
  screener_min_revenue_growth_pct = excluded.screener_min_revenue_growth_pct,
  screener_exchanges = excluded.screener_exchanges,
  screener_max_candidates = excluded.screener_max_candidates;